# Generated by Django 5.2.4 on 2025-07-11 00:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('flow_type', models.CharField(choices=[('initial', 'Saldo Inicial'), ('adjustment', 'Ajuste'), ('transfer', 'Transferência')], max_length=15, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
                ('responsible', models.CharField(choices=[('person1', 'Pessoa 1'), ('person2', 'Pessoa 2'), ('both', 'Ambos')], max_length=10, verbose_name='Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Fluxo de Caixa',
                'verbose_name_plural': 'Fluxos de Caixa',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Cor')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone')),
                ('is_default', models.BooleanField(default=False, verbose_name='Categoria Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['type', 'name'],
                'unique_together': {('name', 'type', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('entry_date', models.DateField(verbose_name='Data do Lançamento')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('due_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dia do Vencimento')),
                ('entry_type', models.CharField(choices=[('fixed', 'Fixa'), ('single', 'Única'), ('installment', 'Parcelada')], max_length=15, verbose_name='Tipo')),
                ('responsible', models.CharField(choices=[('person1', 'Pessoa 1'), ('person2', 'Pessoa 2'), ('both', 'Ambos')], max_length=10, verbose_name='Responsável')),
                ('total_installments', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Parcelas')),
                ('current_installment', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parcela Atual')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado')], default='pending', max_length=10, verbose_name='Status')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(limit_choices_to={'type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, to='financial.category', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('entry_date', models.DateField(verbose_name='Data do Lançamento')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('due_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dia do Vencimento')),
                ('entry_type', models.CharField(choices=[('fixed', 'Fixa'), ('single', 'Única'), ('installment', 'Parcelada')], max_length=15, verbose_name='Tipo')),
                ('responsible', models.CharField(choices=[('person1', 'Pessoa 1'), ('person2', 'Pessoa 2'), ('both', 'Ambos')], max_length=10, verbose_name='Responsável')),
                ('total_installments', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Parcelas')),
                ('current_installment', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parcela Atual')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado')], default='pending', max_length=10, verbose_name='Status')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(limit_choices_to={'type': 'income'}, on_delete=django.db.models.deletion.PROTECT, to='financial.category', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('month', models.IntegerField(verbose_name='Mês')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Receitas')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Despesas')),
                ('fixed_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despesas Fixas')),
                ('installment_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despesas Parceladas')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pendente')),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Atrasado')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resumo Financeiro',
                'verbose_name_plural': 'Resumos Financeiros',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
